---
- name: Create prometheus config directory
  file:
    path: "{{ CONFIG_DIR }}"
    state: directory
    mode: 0755

- name: Copy prometheus config file
  template:
    src: prometheus.j2
    dest: "{{ CONFIG_DIR }}/{{ CONFIG_FILENAME }}"

- name: Start prometheus docker container
  docker_container:
    name: prometheus
    image: prom/prometheus
    network_mode: host
    volumes:
      - /etc/prometheus:/etc/prometheus
    restart_policy: unless-stopped
    command: --web.listen-address 127.0.0.1:"{{ PROM_PORT }}" --config.file="{{ CONFIG_DIR }}/{{ CONFIG_FILENAME }}"
  notify: restart nginx
